import { useCallback, useEffect, useState } from 'react';
import { Activity, Database, Eye, HardDrive, KeyRound, LockKeyhole, LogOut, Save, Server, ShieldCheck, Trash2, UserPlus, Users } from 'lucide-react';
import './Admin.css';

import { featureLabels, vesselFieldLabels, vesselFilterDefinitions, defaultVesselFilters, type VesselFilterConfig } from './adminPolicy';
import type { Flags } from './adminPolicy';
type Session = { user:{ id:number;username:string;role:string;grants:string[] } | null;csrf:string|null };
type ManagedUser = { id:number;username:string;role:string;grants:string[];enabled:boolean;lastLogin:number|null };
type Usage = { accounts:number;enabledAccounts:number;roles:{admin:number;editor:number;viewer:number};activeSessions:number;logins7d:number;created30d:number;views7d:{day:string;views:number}[];viewsToday:number;pages7d:Record<string,number> };
type StorageItem = { id:string;datasetId?:string;label:string;kind:string;rows:number|null;bytes:number|null;deletable:boolean;protected:boolean };
type Storage = { available:boolean;databaseBytes:number|null;sources:number;datasets:number;message?:string;items:StorageItem[] };
type Dashboard = { features:Flags; vesselFields:Record<string,boolean>; vesselFilters:VesselFilterConfig; users:ManagedUser[];audit:{at:number;actor:string;action:string;detail:string}[];statistics:Usage;storage:Storage;status:{diskFreeGb:number;diskTotalGb:number;memoryAvailableMb:number|null;database:string;docker:string;aisFile:boolean;serverTime:number} };
async function api(path:string,method='GET',body?:unknown,csrf?:string) {
 const result=await fetch(path,{method,credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});
 const data=await result.json();
 if (!result.ok) throw new Error(data.error || 'Η ενέργεια απέτυχε.');
 return data;
}
function UsagePanel({ data }: { data: Usage }) {
 const maximum=Math.max(1,...data.views7d.map(item=>item.views));
 const total=Math.max(1,data.accounts);
 const adminShare=data.roles.admin/total*100, editorShare=data.roles.editor/total*100;
 const pageNames:Record<string,string>={map:'Χάρτης',catalog:'Πηγές',seaviolet:'SEAVIOLET',admin:'Διαχείριση'};
 return <section className="admin-panel admin-usage"><div className="admin-panel-title"><div><span className="admin-eyebrow">ΣΤΑΤΙΣΤΙΚΑ</span><h2>Χρήστες & επισκεψιμότητα</h2></div><Users size={23}/></div>
  <div className="admin-usage-kpis"><div><strong>{data.enabledAccounts.toLocaleString('el-GR')}</strong><span>ενεργοί λογαριασμοί</span></div><div><strong>{data.activeSessions.toLocaleString('el-GR')}</strong><span>ανοιχτές συνδέσεις</span></div><div><strong>{data.logins7d.toLocaleString('el-GR')}</strong><span>συνδέσεις 7ημέρου</span></div><div><strong>{data.viewsToday.toLocaleString('el-GR')}</strong><span>προβολές σήμερα</span></div></div>
  <div className="admin-usage-body"><div><h3>Προβολές σελίδων · τελευταίες 7 ημέρες</h3><div className="admin-bars">{data.views7d.map(item=><div key={item.day} className="admin-bar-item" title={item.day+': '+item.views+' προβολές'}><strong>{item.views}</strong><div className="admin-bar-track"><span style={{height:Math.max(item.views ? 9:2,item.views/maximum*100)+'%'}}/></div><small>{new Date(item.day+'T12:00:00').toLocaleDateString('el-GR',{weekday:'short'})}</small></div>)}</div></div>
   <div><h3>Ρόλοι λογαριασμών</h3><div className="admin-roles"><div className="admin-donut" role="img" aria-label={`Διαχειριστές ${data.roles.admin}, συντάκτες ${data.roles.editor}, αναγνώστες ${data.roles.viewer}`} style={{background:`conic-gradient(#087e74 0% ${adminShare}%, #63bdab ${adminShare}% ${adminShare+editorShare}%, #dcece7 ${adminShare+editorShare}% 100%)`}}><strong>{data.accounts}</strong></div><div className="admin-role-legend"><span><i className="admin-role-admin"/>Διαχειριστές <b>{data.roles.admin}</b></span><span><i className="admin-role-editor"/>Συντάκτες <b>{data.roles.editor}</b></span><span><i className="admin-role-viewer"/>Αναγνώστες <b>{data.roles.viewer}</b></span><small>Νέοι λογαριασμοί 30ημέρου: {data.created30d}</small></div></div></div>
  </div><div className="admin-page-counts">{Object.entries(data.pages7d).map(([page,count])=><span key={page}>{pageNames[page]??page}: <b>{count}</b></span>)}</div><p>Οι προβολές είναι ανώνυμα αθροίσματα φορτώσεων σελίδων, όχι μοναδικοί επισκέπτες. Δεν αποθηκεύεται ιστορικό IP ή προσωπική διαδρομή επισκέπτη.</p>
 </section>;
}
const formatBytes=(value:number|null)=>value==null?'—':value<1024*1024?`${Math.round(value/1024).toLocaleString('el-GR')} KB`:`${(value/1024/1024).toLocaleString('el-GR',{maximumFractionDigits:1})} MB`;
function StoragePanel({ data,onDelete }: { data:Storage;onDelete:(item:StorageItem)=>void }) {
 return <section className="admin-panel admin-storage"><div className="admin-panel-title"><div><span className="admin-eyebrow">ΑΠΟΘΗΚΕΥΣΗ</span><h2>Δεδομένα του site</h2></div><HardDrive size={22}/></div>
  <div className="admin-storage-summary"><span><strong>{formatBytes(data.databaseBytes)}</strong> βάση δεδομένων</span><span><strong>{data.sources}</strong> πηγές</span><span><strong>{data.datasets}</strong> σύνολα</span></div>
  {data.message&&<p>{data.message}</p>}
  <div className="admin-table-wrap"><table><thead><tr><th>Αποθηκευμένο σύνολο</th><th>Εγγραφές</th><th>Μέγεθος</th><th>Κατάσταση</th><th>Ενέργεια</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td><strong>{item.label}</strong><small>{item.kind==='source-file'?'Τοπικό αρχείο πηγής':'Δεδομένα PostgreSQL/PostGIS'}</small></td><td>{item.rows==null?'—':item.rows.toLocaleString('el-GR')}</td><td>{formatBytes(item.bytes)}</td><td><span className={item.protected?'admin-protected':'admin-removable'}>{item.protected?'Προστατευμένο':'Διαγράψιμο'}</span></td><td>{item.deletable&&item.rows!==0?<button className="admin-delete" onClick={()=>onDelete(item)}><Trash2 size={14}/> Διαγραφή</button>:<span>—</span>}</td></tr>)}</tbody></table></div>
  <p>Η διαγραφή αφαιρεί τις εισαγμένες εγγραφές από τη βάση και καταγράφεται στο audit. Τα πρωτότυπα αρχεία πηγής παραμένουν προστατευμένα.</p>
 </section>;
}
export function Admin({ onPolicy }: { onPolicy: () => void }) {
 const [session,setSession]=useState<Session | null>(null);
 const [dashboard,setDashboard]=useState<Dashboard | null>(null);
 const [username,setUsername]=useState('');
 const [password,setPassword]=useState('');
 const [error,setError]=useState('');
 const [info,setInfo]=useState('');
 const [newUsername,setNewUsername]=useState('');
 const [newRole,setNewRole]=useState('viewer');
 const [newSeaviolet,setNewSeaviolet]=useState(false);
 const [credential,setCredential]=useState<{username:string;temporaryPassword:string}|null>(null);
 const [currentPass,setCurrentPass]=useState('');
 const [nextPass,setNextPass]=useState('');
 const refresh=useCallback(async () => { const d=await api('/api/admin') as Dashboard;setDashboard(d); },[]);
 useEffect(()=>{ void api('/api/session').then((s:Session)=>{setSession(s);if(s.user?.role==='admin')void refresh().catch(e=>setError(e.message));}).catch(()=>setError('Το διαχειριστικό API δεν έχει ενεργοποιηθεί στον server.')); },[refresh]);
 const run=async (action:()=>Promise<void>)=>{setError('');setInfo('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Άγνωστο σφάλμα.');}};
 const signIn=(event:React.FormEvent)=>{event.preventDefault();void run(async()=>{const s=await api('/api/login','POST',{username,password}) as Session;setSession(s);setPassword('');await refresh();onPolicy();});};
 const saveFlags=()=>{void run(async()=>{if(!session?.csrf||!dashboard)return;await api('/api/admin/flags','PUT',{features:dashboard.features},session.csrf);setInfo('Οι δημόσιες επιλογές εφαρμόστηκαν.');onPolicy();await refresh();});};
 const saveVesselFields=()=>{void run(async()=>{if(!session?.csrf||!dashboard)return;await api('/api/admin/vessel-fields','PUT',{vesselFields:dashboard.vesselFields},session.csrf);setInfo('Τα στοιχεία του πλοίου αποθηκεύτηκαν.');await refresh();});};
 const saveVesselFilters=()=>{void run(async()=>{if(!session?.csrf||!dashboard)return;await api('/api/admin/vessel-filters','PUT',{vesselFilters:dashboard.vesselFilters},session.csrf);setInfo('Τα φίλτρα του SEAVIOLET αποθηκεύτηκαν.');await refresh();});};
 const addUser=(event:React.FormEvent)=>{event.preventDefault();void run(async()=>{if(!session?.csrf)return;const d=await api('/api/admin/users','POST',{username:newUsername,role:newRole,grants:newSeaviolet?['seaviolet:view']:[]},session.csrf);setCredential(d);setNewUsername('');await refresh();});};
 const updateUser=(u:ManagedUser)=>{void run(async()=>{if(!session?.csrf)return;await api('/api/admin/users/'+u.id,'PATCH',{role:u.role,enabled:u.enabled,grants:u.grants},session.csrf);setInfo('Τα δικαιώματα αποθηκεύτηκαν.');await refresh();onPolicy();});};
 const changePassword=(event:React.FormEvent)=>{event.preventDefault();void run(async()=>{if(!session?.csrf)return;await api('/api/password','POST',{current:currentPass,new:nextPass},session.csrf);setCurrentPass('');setNextPass('');setInfo('Ο κωδικός ενημερώθηκε.');});};
 const logout=()=>{void run(async()=>{if(!session?.csrf)return;await api('/api/logout','POST',{},session.csrf);setSession({user:null,csrf:null});setDashboard(null);onPolicy();});};
 const deleteStorage=(item:StorageItem)=>{if(!window.confirm(`Να διαγραφούν ${item.rows?.toLocaleString('el-GR')??'όλες οι'} εγγραφές από «${item.label}»;`))return;void run(async()=>{if(!session?.csrf)return;const result=await api('/api/admin/storage','DELETE',{kind:item.kind,datasetId:item.datasetId},session.csrf);setInfo(`Διαγράφηκαν ${Number(result.deleted).toLocaleString('el-GR')} εγγραφές.`);await refresh();});};
 const updateLocalUser=(id:number,patch:Partial<ManagedUser>)=>setDashboard(prev=>prev?{...prev,users:prev.users.map(u=>u.id===id?{...u,...patch}:u)}:prev);
 const updateLocalFilter=(key:string,patch:Partial<VesselFilterConfig[string]>)=>setDashboard(prev=>{if(!prev)return prev;const current=prev.vesselFilters[key]??defaultVesselFilters[key];return {...prev,vesselFilters:{...prev.vesselFilters,[key]:{...current,...patch}}};});
 const toggleFilterOption=(key:string,option:string,checked:boolean)=>setDashboard(prev=>{if(!prev)return prev;const current=prev.vesselFilters[key]??defaultVesselFilters[key];const options=checked?[...new Set([...current.options,option])]:current.options.filter(item=>item!==option);if(!options.length)return prev;return {...prev,vesselFilters:{...prev.vesselFilters,[key]:{...current,options}}};});
 return <div className="admin-page"><div className="admin-header"><span className="admin-eyebrow"><ShieldCheck size={16}/> KAPAVITA CONTROL</span><h1>Κέντρο διαχείρισης</h1><p>Πολιτικές προβολής, λογαριασμοί και πραγματική κατάσταση υποδομής.</p></div>
 {error&&<div className="admin-alert" role="alert">{error}</div>}{info&&<div className="admin-success" role="status">{info}</div>}
 {!session?.user ? <form className="admin-login" onSubmit={signIn}><LockKeyhole size={27}/><h2>Σύνδεση διαχειριστή</h2><label>Όνομα χρήστη<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Κωδικός<input autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button type="submit">Σύνδεση</button><small>Η πρόσβαση ελέγχεται στον server. Δεν υπάρχει προεπιλεγμένος κωδικός.</small></form>
 : session.user.role!=='admin' ? <section className="admin-panel"><h2>Λογαριασμός {session.user.username}</h2><p>Ο ρόλος σου είναι {session.user.role}. Οι αλλαγές πολιτικών απαιτούν δικαιώματα διαχειριστή.</p><form className="admin-password" onSubmit={changePassword}><label>Άλλαξε τον προσωρινό κωδικό<input type="password" autoComplete="current-password" placeholder="Τωρινός κωδικός" value={currentPass} onChange={e=>setCurrentPass(e.target.value)} required/></label><input type="password" autoComplete="new-password" placeholder="Νέος κωδικός (12+ χαρακτήρες)" value={nextPass} onChange={e=>setNextPass(e.target.value)} minLength={12} required/><button>Αλλαγή κωδικού</button></form><button className="admin-secondary" onClick={logout}>Αποσύνδεση</button></section>
 : <><div className="admin-welcome"><span>Συνδεδεμένος: <strong>{session.user.username}</strong> · Διαχειριστής</span><button onClick={logout}><LogOut size={15}/> Αποσύνδεση</button></div>
 {dashboard&&<><div className="admin-metrics"><div><Server size={22}/><span>Χώρος δίσκου</span><strong>{dashboard.status.diskFreeGb} / {dashboard.status.diskTotalGb} GB</strong><small>ελεύθερα / σύνολο</small></div><div><Activity size={22}/><span>Διαθέσιμη μνήμη</span><strong>{dashboard.status.memoryAvailableMb??'—'} MB</strong><small>στο VPS, τη στιγμή ελέγχου</small></div><div><Database size={22}/><span>Βάση & Docker</span><strong>{dashboard.status.docker}</strong><small>{dashboard.status.database}</small></div><div><Eye size={22}/><span>SEAVIOLET / AIS</span><strong>{dashboard.status.aisFile?'Υπάρχει τελευταίο στίγμα':'Αναμονή στίγματος'}</strong><small>Δεδομένα και δικαίωμα προβολής ελέγχονται χωριστά</small></div></div>
 <UsagePanel data={dashboard.statistics}/>
 <StoragePanel data={dashboard.storage} onDelete={deleteStorage}/>
 <div className="admin-grid"><section className="admin-panel"><div className="admin-panel-title"><div><span className="admin-eyebrow">ΑΡΧΙΚΗ ΣΕΛΙΔΑ</span><h2>Τι βλέπει ο επισκέπτης</h2></div><button className="admin-save" onClick={saveFlags}><Save size={16}/> Αποθήκευση</button></div><p>Όταν απενεργοποιείς ένα επίπεδο, αφαιρείται από τον δημόσιο χάρτη και την αναζήτηση. Τα υποκείμενα δημόσια αρχεία γεωγραφικών ορίων παραμένουν δημόσια.</p><div className="admin-switches">{Object.entries(featureLabels).map(([key,label])=><label key={key}><span>{label}{key==='seaviolet'&&<small>Προεπιλογή: μόνο σε εξουσιοδοτημένους λογαριασμούς.</small>}</span><input type="checkbox" checked={dashboard.features[key]} onChange={e=>setDashboard(prev=>prev?{...prev,features:{...prev.features,[key]:e.target.checked}}:prev)}/></label>)}</div></section>
 <section className="admin-panel"><div className="admin-panel-title"><div><span className="admin-eyebrow">SEAVIOLET</span><h2>Τι βλέπει ο απλός χρήστης</h2></div><button className="admin-save" onClick={saveVesselFields}><Save size={16}/> Αποθήκευση</button></div><p>Επίλεξε ποια στοιχεία του πλοίου θα εμφανίζονται στη δημόσια καρτέλα και στον χάρτη. Η επιλογή εφαρμόζεται άμεσα μετά την αποθήκευση.</p><div className="admin-switches">{Object.entries(vesselFieldLabels).map(([key,label])=><label key={key}><span>{label}</span><input type="checkbox" checked={dashboard.vesselFields[key] ?? false} onChange={e=>setDashboard(prev=>prev?{...prev,vesselFields:{...prev.vesselFields,[key]:e.target.checked}}:prev)}/></label>)}</div></section>
 <section className="admin-panel admin-filter-panel"><div className="admin-panel-title"><div><span className="admin-eyebrow">SEAVIOLET · ΦΙΛΤΡΑ</span><h2>Τι μπορεί να φιλτράρει ο χρήστης</h2></div><button className="admin-save" onClick={saveVesselFilters}><Save size={16}/> Αποθήκευση</button></div><p>Άνοιξε ή κλείσε κάθε φίλτρο και επίλεξε ποιες επιλογές θα προσφέρονται στη δημόσια καρτέλα του πλοίου.</p><div className="admin-filter-cards">{Object.entries(vesselFilterDefinitions).map(([key,definition])=>{const state=dashboard.vesselFilters[key]??defaultVesselFilters[key];return <div className="admin-filter-card" key={key}><label className="admin-filter-toggle"><span><strong>{definition.label}</strong><small>{definition.description}</small></span><input type="checkbox" checked={state.enabled} onChange={e=>updateLocalFilter(key,{enabled:e.target.checked})}/></label><div className="admin-filter-options"><span>Διαθέσιμες επιλογές</span>{Object.entries(definition.options).map(([option,label])=><label key={option}><input type="checkbox" checked={state.options.includes(option)} disabled={!state.enabled} onChange={e=>toggleFilterOption(key,option,e.target.checked)}/>{label}</label>)}</div></div>})}</div></section>
 <section className="admin-panel"><span className="admin-eyebrow">ΥΠΟΔΟΜΗ</span><h2>Κατάσταση έργου</h2><div className="admin-status-list"><div><span>API λογαριασμών</span><strong>Ενεργό</strong></div><div><span>Βάση ρυθμίσεων</span><strong>SQLite · ενεργή</strong></div><div><span>Docker / PostgreSQL</span><strong>{dashboard.status.docker}</strong></div><div><span>Τελευταίο AIS</span><strong>{dashboard.status.aisFile?'Αρχείο διαθέσιμο':'Δεν έχει παραληφθεί'}</strong></div></div><p>Η PostgreSQL/PostGIS θα συνδεθεί όταν εγκατασταθεί. Δεν παρουσιάζονται εικονικές μετρήσεις βάσης.</p><button className="admin-secondary" onClick={()=>void run(refresh)}>Ανανέωση μετρήσεων</button></section></div>
 <section className="admin-panel"><div className="admin-panel-title"><div><span className="admin-eyebrow">ΠΡΟΣΒΑΣΗ</span><h2>Χρήστες και δικαιώματα</h2></div><Users size={21}/></div><div className="admin-table-wrap"><table><thead><tr><th>Χρήστης</th><th>Ρόλος</th><th>SEAVIOLET</th><th>Ενεργός</th><th>Ενέργεια</th></tr></thead><tbody>{dashboard.users.map(u=><tr key={u.id}><td><strong>{u.username}</strong><small>{u.lastLogin?'Τελευταία σύνδεση '+new Date(u.lastLogin*1000).toLocaleString('el-GR'):'Δεν έχει συνδεθεί'}</small></td><td><select value={u.role} onChange={e=>updateLocalUser(u.id,{role:e.target.value})}><option value="viewer">Αναγνώστης</option><option value="editor">Συντάκτης</option><option value="admin">Διαχειριστής</option></select></td><td><input aria-label={'Πρόσβαση SEAVIOLET '+u.username} type="checkbox" checked={u.grants.includes('seaviolet:view')} onChange={e=>updateLocalUser(u.id,{grants:e.target.checked?['seaviolet:view']:[]})}/></td><td><input aria-label={'Ενεργός '+u.username} type="checkbox" checked={u.enabled} onChange={e=>updateLocalUser(u.id,{enabled:e.target.checked})}/></td><td><button className="admin-secondary" onClick={()=>updateUser(u)}>Αποθήκευση</button></td></tr>)}</tbody></table></div>
 <form className="admin-add-user" onSubmit={addUser}><UserPlus size={18}/><label>Νέος χρήστης<input value={newUsername} onChange={e=>setNewUsername(e.target.value)} required minLength={3} placeholder="π.χ. family_1"/></label><label>Ρόλος<select value={newRole} onChange={e=>setNewRole(e.target.value)}><option value="viewer">Αναγνώστης</option><option value="editor">Συντάκτης</option><option value="admin">Διαχειριστής</option></select></label><label className="admin-check"><input type="checkbox" checked={newSeaviolet} onChange={e=>setNewSeaviolet(e.target.checked)}/> Πρόσβαση SEAVIOLET</label><button type="submit">Προσθήκη</button></form>
 {credential&&<div className="admin-credential"><KeyRound size={20}/><div><strong>Προσωρινός κωδικός για {credential.username}</strong><code>{credential.temporaryPassword}</code><small>Εμφανίζεται μόνο τώρα. Μετά τη σύνδεση να αλλάξει κωδικό. Μην τον στέλνεις δημόσια.</small></div><button onClick={()=>setCredential(null)}>Κλείσιμο</button></div>}</section>
 <div className="admin-grid"><section className="admin-panel"><span className="admin-eyebrow">ΑΣΦΑΛΕΙΑ</span><h2>Αλλαγή κωδικού</h2><form className="admin-password" onSubmit={changePassword}><input type="password" autoComplete="current-password" placeholder="Τωρινός κωδικός" value={currentPass} onChange={e=>setCurrentPass(e.target.value)} required/><input type="password" autoComplete="new-password" placeholder="Νέος κωδικός (12+ χαρακτήρες)" value={nextPass} onChange={e=>setNextPass(e.target.value)} minLength={12} required/><button>Αλλαγή</button></form></section><section className="admin-panel"><span className="admin-eyebrow">ΚΑΤΑΓΡΑΦΗ</span><h2>Πρόσφατες ενέργειες</h2><div className="admin-audit">{dashboard.audit.map((e,i)=><div key={i}><time>{new Date(e.at*1000).toLocaleString('el-GR')}</time><strong>{e.action}</strong><span>{e.actor} · {e.detail}</span></div>)}</div></section></div>
 </>}</>}
 </div>;
}
