import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowRight, Boxes, FileText, KeyRound, LockKeyhole, LogOut, MapPin, Plus, RefreshCw, ShieldCheck, Users, WalletCards, X } from 'lucide-react';
import { Responsive, WidthProvider, type Layout } from 'react-grid-layout/legacy';
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';
import './KVWorkspace.css';

const ResponsiveGrid = WidthProvider(Responsive);
type SessionUser = { id:number; username:string; role:string; grants:string[] };
type Session = { user:SessionUser|null; csrf:string|null };
type EntityType = 'person'|'company'|'place'|'property'|'asset'|'vehicle'|'account'|'device'|'document';
type Entity = { id:string; type:EntityType; name:string; sensitivity:string; ownerUserId:number; metadata:Record<string,unknown>; createdAt:string; updatedAt:string };
type Connector = { id:string; label:string; status:string };
type KVLayouts = Partial<Record<string,Layout>>;
type Bootstrap = { user:SessionUser; entities:Entity[]; entityCounts:Record<EntityType,number>; layout:Layout; connectorStates:Connector[]; securityFoundation:{ denyByDefault:boolean; adminLocationOverride:boolean; serverSecretsOnly:boolean; locationConsentRequired:boolean; twoFactor:string; passkeys:string } };
const entityLabels:Record<EntityType,string>={person:'People',company:'Companies',place:'Places',property:'Properties',asset:'Assets',vehicle:'Vehicles',account:'Accounts',device:'Devices',document:'Documents'};
const entityIcons:Record<EntityType,typeof Users>={person:Users,company:Boxes,place:MapPin,property:MapPin,asset:Boxes,vehicle:Activity,account:WalletCards,device:ShieldCheck,document:FileText};
const defaultLayouts:KVLayouts={lg:[{i:'attention',x:0,y:0,w:6,h:2},{i:'entities',x:6,y:0,w:6,h:2},{i:'connectors',x:0,y:2,w:4,h:2},{i:'security',x:4,y:2,w:8,h:2}],md:[{i:'attention',x:0,y:0,w:6,h:2},{i:'entities',x:6,y:0,w:6,h:2},{i:'connectors',x:0,y:2,w:6,h:2},{i:'security',x:6,y:2,w:6,h:2}],sm:[{i:'attention',x:0,y:0,w:6,h:2},{i:'entities',x:0,y:2,w:6,h:3},{i:'connectors',x:0,y:5,w:6,h:3},{i:'security',x:0,y:8,w:6,h:3}]};
async function api(path:string,method='GET',body?:unknown,csrf?:string|null){
 const response=await fetch(path,{method,credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});
 const data=await response.json();
 if(!response.ok)throw new Error(data.error||'Η ενέργεια απέτυχε.');
 return data;
}
function LoginGate({onSignedIn}:{onSignedIn:(session:Session)=>void}){
 const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{onSignedIn(await api('/api/login','POST',{username,password}) as Session);setPassword('');}catch(error){setError(error instanceof Error?error.message:'Η σύνδεση απέτυχε.');}finally{setBusy(false);}};
 return <div className="kv-login-wrap"><form className="kv-login-card" onSubmit={submit}><div className="kv-login-mark"><LockKeyhole size={22}/></div><span className="kv-eyebrow">KV PRIVATE WORKSPACE</span><h2>Μπες στον χώρο σου.</h2><p>Η πρόσβαση ελέγχεται στον server. Οι οντότητες και τα dashboard layouts είναι ιδιωτικά από προεπιλογή.</p>{error&&<div className="kv-alert" role="alert">{error}</div>}<label>Όνομα χρήστη<input autoComplete="username" value={username} onChange={event=>setUsername(event.target.value)} required/></label><label>Κωδικός<input autoComplete="current-password" type="password" value={password} onChange={event=>setPassword(event.target.value)} required/></label><button className="kv-primary" disabled={busy}>{busy?'Έλεγχος…':'Σύνδεση στο KV'}</button><small>2FA, passkeys και trusted devices είναι foundation capabilities που ενεργοποιούνται σε επόμενο hardening step.</small></form></div>;
}
function WidgetFrame({title,eyebrow,icon:Icon,children}:{title:string;eyebrow:string;icon:typeof Activity;children:React.ReactNode}){return <section className="kv-widget"><header><span className="kv-widget-icon"><Icon size={17}/></span><div><span className="kv-eyebrow">{eyebrow}</span><h3>{title}</h3></div><button className="kv-icon-button" aria-label="Περισσότερες επιλογές"><ArrowRight size={16}/></button></header>{children}</section>}
function KVWorkspace(){
 const [session,setSession]=useState<Session|null>(null); const [bootstrap,setBootstrap]=useState<Bootstrap|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [newType,setNewType]=useState<EntityType>('person'); const [newName,setNewName]=useState(''); const [saving,setSaving]=useState(false); const saveTimer=useRef<number|undefined>(undefined);
 useEffect(()=>{void api('/api/session').then((value:Session)=>setSession(value)).catch(()=>setError('Το KV API δεν είναι διαθέσιμο.')).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!session?.user){setBootstrap(null);return;}setLoading(true);void api('/api/kv/bootstrap').then((value:Bootstrap)=>{setBootstrap(value);setError('');}).catch(error=>setError(error instanceof Error?error.message:'Το KV foundation δεν είναι διαθέσιμο.')).finally(()=>setLoading(false));},[session]);
 const layouts=useMemo<KVLayouts>(()=>bootstrap?{lg:bootstrap.layout,md:bootstrap.layout,sm:bootstrap.layout}:defaultLayouts,[bootstrap]);
 const saveLayout=(next:KVLayouts)=>{if(!session?.csrf)return;window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>{const layout=next.lg??next.md??next.sm??[];void api('/api/kv/layout','PUT',{layout},session.csrf).then(()=>setBootstrap(previous=>previous?{...previous,layout}:previous)).catch(error=>setError(error instanceof Error?error.message:'Η διάταξη δεν αποθηκεύτηκε.'));},350);};
 const createEntity=async(event:React.FormEvent)=>{event.preventDefault();if(!session?.csrf||!newName.trim())return;setSaving(true);try{const result=await api('/api/kv/entities','POST',{type:newType,name:newName.trim(),sensitivity:'private',metadata:{}},session.csrf);setBootstrap(previous=>previous?{...previous,entities:[result.entity,...previous.entities],entityCounts:{...previous.entityCounts,[newType]:previous.entityCounts[newType]+1}}:previous);setNewName('');}catch(error){setError(error instanceof Error?error.message:'Η οντότητα δεν αποθηκεύτηκε.');}finally{setSaving(false);}};
 if(loading&&!session)return <div className="kv-page"><div className="kv-loading">Φόρτωση ασφαλούς χώρου…</div></div>;
 if(!session?.user)return <div className="kv-page"><LoginGate onSignedIn={setSession}/></div>;
 if(!bootstrap)return <div className="kv-page"><div className="kv-loading">{error||'Φόρτωση KV foundation…'}</div></div>;
 const logout=async()=>{if(session.csrf){await api('/api/logout','POST',{},session.csrf).catch(()=>{});}setSession({user:null,csrf:null});};
 const totalEntities=bootstrap.entities.length; const readyConnectors=bootstrap.connectorStates.filter(item=>item.status==='ready').length;
 return <div className="kv-page"><header className="kv-topbar"><div className="kv-brand"><span className="kv-brand-mark"><span/></span><div><strong>KV<span>.gr</span></strong><small>PRIVATE OPERATING SPACE</small></div></div><nav><a className="active" href="/kv">Workspace</a><a href="/">Spatial Intelligence</a></nav><div className="kv-top-actions"><span className="kv-user"><span className="kv-online-dot"/>{bootstrap.user.username}</span><button className="kv-icon-button" onClick={()=>void logout()} aria-label="Αποσύνδεση"><LogOut size={17}/></button></div></header>
 <main className="kv-main"><aside className="kv-sidebar"><span className="kv-eyebrow">KV V1 FOUNDATION</span><h1>Ο χώρος σου,<br/><em>σε ένα σημείο.</em></h1><p>Μια ασφαλής βάση για ανθρώπους, οργανισμούς, χώρους και assets. Οι συνδέσεις έρχονται όταν υπάρχει πραγματική, ελεγμένη πρόσβαση.</p><div className="kv-sidebar-card"><ShieldCheck size={18}/><div><strong>Private by default</strong><small>Server-side permissions και audit foundation ενεργά.</small></div></div><form className="kv-create" onSubmit={createEntity}><span className="kv-eyebrow">ΝΕΑ ΟΝΤΟΤΗΤΑ</span><select value={newType} onChange={event=>setNewType(event.target.value as EntityType)}>{(Object.keys(entityLabels) as EntityType[]).map(type=><option key={type} value={type}>{entityLabels[type]}</option>)}</select><input value={newName} onChange={event=>setNewName(event.target.value)} placeholder="Όνομα, π.χ. Οικογένεια" required/><button className="kv-primary" disabled={saving}><Plus size={16}/>{saving?'Αποθήκευση…':'Προσθήκη'}</button></form><div className="kv-side-note"><KeyRound size={15}/><span>Credentials και connector secrets δεν περνούν στον browser.</span></div></aside>
 <section className="kv-workspace"><div className="kv-workspace-heading"><div><span className="kv-eyebrow">TODAY · {new Date().toLocaleDateString('el-GR',{day:'2-digit',month:'long',year:'numeric'})}</span><h2>Καλημέρα, {bootstrap.user.username}.</h2><p>Το foundation είναι έτοιμο για τις πρώτες δικές σου οντότητες.</p></div><button className="kv-secondary" onClick={()=>window.location.reload()}><RefreshCw size={15}/> Ανανέωση</button></div>{error&&<div className="kv-alert" role="alert">{error}<button onClick={()=>setError('')}><X size={14}/></button></div>}
 <ResponsiveGrid className="kv-grid" layouts={layouts} breakpoints={{lg:1100,md:780,sm:0}} cols={{lg:12,md:12,sm:6}} rowHeight={92} margin={[16,16]} containerPadding={[0,0]} onLayoutChange={(_,all)=>saveLayout(all)} draggableHandle=".kv-drag-handle">
  <div key="attention"><WidgetFrame title="KV Attention" eyebrow="ATTENTION / ACTIONS" icon={Activity}><div className="kv-widget-empty"><strong>Δεν υπάρχουν εκκρεμείς ενέργειες.</strong><span>Το κέντρο προσοχής θα εμφανίζει verified changes από συνδεδεμένα συστήματα.</span></div></WidgetFrame></div>
  <div key="entities"><WidgetFrame title="Οντότητες" eyebrow="YOUR GRAPH" icon={Boxes}><div className="kv-entity-grid">{(Object.keys(entityLabels) as EntityType[]).map(type=>{const Icon=entityIcons[type];return <div className="kv-entity-stat" key={type}><Icon size={16}/><strong>{bootstrap.entityCounts[type]??0}</strong><span>{entityLabels[type]}</span></div>;})}</div></WidgetFrame></div>
  <div key="connectors"><WidgetFrame title="Connectors" eyebrow="EXTENSION POINTS" icon={Activity}><div className="kv-connector-list">{bootstrap.connectorStates.slice(0,4).map(item=><div key={item.id}><span className="kv-status-dot"/><span>{item.label}</span><small>{item.status==='ready'?'Ready':item.status==='consent-required'?'Consent':'Planned'}</small></div>)}</div><small className="kv-muted">{readyConnectors} ενεργές συνδέσεις · {bootstrap.connectorStates.length} extension points</small></WidgetFrame></div>
  <div key="security"><WidgetFrame title="Security foundation" eyebrow="TRUST BOUNDARY" icon={ShieldCheck}><div className="kv-security-grid"><div><strong>{bootstrap.securityFoundation.denyByDefault?'Ενεργό':'—'}</strong><span>Deny by default</span></div><div><strong>{bootstrap.securityFoundation.serverSecretsOnly?'Server-side':'—'}</strong><span>Secrets</span></div><div><strong>{bootstrap.securityFoundation.locationConsentRequired?'Απαιτείται':'—'}</strong><span>Location consent</span></div><div><strong>{bootstrap.securityFoundation.adminLocationOverride?'Ναι':'Όχι'}</strong><span>Admin location override</span></div></div><p className="kv-widget-footnote">2FA, passkeys, trusted devices και αναλυτικό device management είναι οι επόμενες hardening capabilities.</p></WidgetFrame></div>
 </ResponsiveGrid>
 <section className="kv-entity-strip"><div><span className="kv-eyebrow">RECENT PRIVATE ENTITIES</span><h3>{totalEntities?`${totalEntities} οντότητες στον χώρο σου`:'Ξεκίνα με την πρώτη οντότητα'}</h3></div><div className="kv-recent-list">{bootstrap.entities.slice(0,5).map(entity=>{const Icon=entityIcons[entity.type];return <span key={entity.id}><Icon size={14}/>{entity.name}</span>})}{!totalEntities&&<span className="kv-muted">Δεν αποθηκεύτηκε προσωπικό δεδομένο ακόμη.</span>}</div></section>
 </section></main></div>;
}
export default KVWorkspace;
